window.onload = function() {
  var button = document.getElementById('button');
  var content = document.getElementById('content');

  var currFable; //will hold the index of the currently shown fable

  console.log(content);
  var fables = [ //randomly picking one of these fables to display. stored here to be sure it works offline.
    "<h1>Belling the Cat</h1><p>Long ago, the mice had a general council to consider what measures they could take to outwit their common enemy, the Cat.</p><p><i>\"You will all agree,\"</i> said he, <i>\"that our chief danger consists in the sly and treacherous manner in which the enemy approaches us. Now, if we could receive some signal of her approach, we could easily escape from her. I venture, therefore, to propose that a small bell be procured, and attached by a ribbon round the neck of the Cat. By this means we should always know when she was about, and could easily retire while she was in the neighbourhood.\"</i></p><p>This proposal met with general applause, until an old mouse got up and said:</p><p><i>\"That is all very well, but who is to bell the Cat?\"</i></p><p>The mice looked at one another and nobody spoke. Then the old mouse said:</p><p><i>\"It is easy to propose impossible remedies.\"</i></p>",
    "<h1>Androcles</h1><p>A slave named Androcles once escaped from his master and fled to the forest. As he was wandering about there he came upon a Lion lying down moaning and groaning. At first he turned to flee, but finding that the Lion did not pursue him, he turned back and went up to him.</p><p>As he came near, the Lion put out his paw, which was all swollen and bleeding, and Androcles found that a huge thorn had got into it, and was causing all the pain. He pulled out the thorn and bound up the paw of the Lion, who was soon able to rise and lick the hand of Androcles like a dog. Then the Lion took Androcles to his cave, and every day used to bring him meat from which to live.</p><p>But shortly afterwards both Androcles and the Lion were captured, and the slave was sentenced to be thrown to the Lion, after the latter had been kept without food for several days. The Emperor and all his Court came to see the spectacle, and Androcles was led out into the middle of the arena. Soon the Lion was let loose from his den, and rushed bounding and roaring towards his victim.</p><p>But as soon as he came near to Androcles he recognised his friend, and fawned upon him, and licked his hands like a friendly dog. The Emperor, surprised at this, summoned Androcles to him, who told him the whole story. Whereupon the slave was pardoned and freed, and the Lion let loose to his native forest.</p>",
    "<h1>The Frogs & the Ox</h1><p>An Ox came down to a reedy pool to drink. As he splashed heavily into the water, he crushed a young Frog into the mud.</p><p>The old Frog soon missed the little one and asked his brothers and sisters what had become of him</p><p><em>\"A great big monster,\"</em> said one of them, <em>\"stepped on little brother with one of his huge feet!\"</em></p><p><em>\"Big, was he!\"</em> said the old Frog, puffing herself up. <em>\"Was he as big as this?\"</em></p><p><em>\"Oh, much bigger!\"</em> they cried.</p><p>The Frog puffed up still more.</p><p><em>\"He could not have been bigger than this,\"</em> she said. But the little Frogs all declared that the monster was much, much bigger and the old Frog kept puffing herself out more and more until, all at once, she burst.</p><p>Do not attempt the impossible.</p>",
    "<h1>The Town Mouse & the Country Mouse</h1><p>A Town Mouse once visited a relative who lived in the country. For lunch the Country Mouse served wheat stalks, roots, and acorns, with a dash of cold water for drink. The Town Mouse ate very sparingly, nibbling a little of this and a little of that, and by her manner making it very plain that she ate the simple food only to be polite.</p><p>After the meal the friends had a long talk, or rather the Town Mouse talked about her life in the city while the Country Mouse listened. They then went to bed in a cozy nest in the hedgerow and slept in quiet and comfort until morning. In her sleep the Country Mouse dreamed she was a Town Mouse with all the luxuries and delights of city life that her friend had described for her. So the next day when the Town Mouse asked the Country Mouse to go home with her to the city, she gladly said yes.</p><p>When they reached the mansion in which the Town Mouse lived, they found on the table in the dining room the leavings of a very fine banquet. There were sweetmeats and jellies, pastries, delicious cheeses, indeed, the most tempting foods that a Mouse can imagine. But just as the Country Mouse was about to nibble a dainty bit of pastry, she heard a Cat mew loudly and scratch at the door. In great fear the Mice scurried to a hiding place, where they lay quite still for a long time, hardly daring to breathe. When at last they ventured back to the feast, the door opened suddenly and in came the servants to clear the table, followed by the House Dog.</p><div>&nbsp;</div><p>The Country Mouse stopped in the Town Mouse's den only long enough to pick up her carpet bag and umbrella.</p><p>\"You may have luxuries and dainties that I have not,\" she said as she hurried away, \"but I prefer my plain food and simple life in the country with the peace and security that go with it.\"</p><p>Poverty with security is better than plenty in the midst of fear and uncertainty.</p>",
    "<h1>The Fox & the Grapes</h1><p>A Fox one day spied a beautiful bunch of ripe grapes hanging from a vine trained along the branches of a tree. The grapes seemed ready to burst with juice, and the Fox's mouth watered as he gazed longingly at them.</p><p>The bunch hung from a high branch, and the Fox had to jump for it. The first time he jumped he missed it by a long way. So he walked off a short distance and took a running leap at it, only to fall short once more. Again and again he tried, but in vain.</p><p>Now he sat down and looked at the grapes in disgust.</p><p>\"What a fool I am,\" he said. \"Here I am wearing myself out to get a bunch of sour grapes that are not worth gaping for.\"</p><p>And off he walked very, very scornfully.</p><p>There are many who pretend to despise and belittle that which is beyond their reach.</p>",
    "<h1>The Wolf & the Crane</h1><p>A Wolf had been feasting too greedily, and a bone had stuck crosswise in his throat. He could get it neither up nor down, and of course he could not eat a thing. Naturally that was an awful state of affairs for a greedy Wolf.</p><p>So away he hurried to the Crane. He was sure that she, with her long neck and bill, would easily be able to reach the bone and pull it out.</p><p>\"I will reward you very handsomely,\" said the Wolf, \"if you pull that bone out for me.\"</p><p>The Crane, as you can imagine, was very uneasy about putting her head in a Wolf\'s throat. But she was grasping in nature, so she did what the Wolf asked her to do.</p><p>When the Wolf felt that the bone was gone, he started to walk away.</p><p>\"But what about my reward!\" called the Crane anxiously.</p><p>\"What!\" snarled the Wolf, whirling around. \"Haven't you got it? Isn't it enough that I let you take your head out of my mouth without snapping it off?\"</p><p>Expect no reward for serving the wicked.</p>",
    "<h1>The Lion & the Mouse</h1><p>A Lion lay asleep in the forest, his great head resting on his paws. A timid little Mouse came upon him unexpectedly, and in her fright and haste to get away, ran across the Lion's nose. Roused from his nap, the Lion laid his huge paw angrily on the tiny creature to kill her.</p><p>\"Spare me!\" begged the poor Mouse. \"Please let me go and some day I will surely repay you.\"</p><p>The Lion was much amused to think that a Mouse could ever help him. But he was generous and finally let the Mouse go.</p><p>Some days later, while stalking his prey in the forest, the Lion was caught in the toils of a hunter's net. Unable to free himself, he filled the forest with his angry roaring. The Mouse knew the voice and quickly found the Lion struggling in the net. Running to one of the great ropes that bound him, she gnawed it until it parted, and soon the Lion was free.</p><p>\"You laughed when I said I would repay you,\" said the Mouse. \"Now you see that even a Mouse can help a Lion.\"</p><p>A kindness is never wasted.</p>",
    "<h1>The Gnat & the Bull</h1><p>A Gnat flew over the meadow with much buzzing for so small a creature and settled on the tip of one of the horns of a Bull. After he had rested a short time, he made ready to fly away. But before he left he begged the Bull's pardon for having used his horn for a resting place.</p><p>\"You must be very glad to have me go now,\" he said.</p><p>\"It's all the same to me,\" replied the Bull. \"I did not even know you were there.\"</p><p>We are often of greater importance in our own eyes than in the eyes of our neighbor. The smaller the mind the greater the conceit.</p>",
    "<h1>The Plane Tree</h1><p>Two Travellers, walking in the noonday sun, sought the shade of a widespreading tree to rest. As they lay looking up among the pleasant leaves, they saw that it was a Plane Tree.</p><p>\"How useless is the Plane!\" said one of them. \"It bears no fruit whatever, and only serves to litter the ground with leaves.\"</p><p>\"Ungrateful creatures!\" said a voice from the Plane Tree. \"You lie here in my cooling shade, and yet you say I am useless! Thus ungratefully, O Jupiter, do men receive their blessings!\"</p><p>Our best blessings are often the least appreciated.</p>",
    "<h1>The Owl & the Grasshopper</h1><p>The Owl always takes her sleep during the day. Then after sundown, when the rosy light fades from the sky and the shadows rise slowly through the wood, out she comes ruffling and blinking from the old hollow tree. Now her weird \"hoo-hoo-hoo-oo-oo\" echoes through the quiet wood, and she begins her hunt for the bugs and beetles, frogs and mice she likes so well to eat.</p><p>Now there was a certain old Owl who had become very cross and hard to please as she grew older, especially if anything disturbed her daily slumbers. One warm summer afternoon as she dozed away in her den in the old oak tree, a Grasshopper nearby began a joyous but very raspy song. Out popped the old Owl\'s head from the opening in the tree that served her both for door and for window.</p><p>\"Get away from here, sir,\" she said to the Grasshopper. \"Have you no manners? You should at least respect my age and leave me to sleep in quiet!\"</p><p>But the Grasshopper answered saucily that he had as much right to his place in the sun as the Owl had to her place in the old oak. Then he struck up a louder and still more rasping tune.</p><p>The wise old Owl knew quite well that it would do no good to argue with the Grasshopper, nor with anybody else for that matter. Besides, her eyes were not sharp enough by day to permit her to punish the Grasshopper as he deserved. So she laid aside all hard words and spoke very kindly to him.</p><p>\"Well sir,\" she said, \"if I must stay awake, I am going to settle right down to enjoy your singing. Now that I think of it, I have a wonderful wine here, sent me from Olympus, of which I am told Apollo drinks before he sings to the high gods. Please come up and taste this delicious drink with me. I know it will make you sing like Apollo himself.\"</p><div>&nbsp;</div><p>The foolish Grasshopper was taken in by the Owl\'s flattering words. Up he jumped to the Owl\'s den, but as soon as he was near enough so the old Owl could see him clearly, she pounced upon him and ate him up.</p><p>Flattery is not a proof of true admiration. Do not let flattery throw you off your guard against an enemy.</p>",
    "<h1>The Oak & the Reeds</h1><p>A Giant Oak stood near a brook in which grew some slender Reeds. When the wind blew, the great Oak stood proudly upright with its hundred arms uplifted to the sky. But the Reeds bowed low in the wind and sang a sad and mournful song.</p><p>\"You have reason to complain,\" said the Oak. \"The slightest breeze that ruffles the surface of the water makes you bow your heads, while I, the mighty Oak, stand upright and firm before the howling tempest.\"</p><p>\"Do not worry about us,\" replied the Reeds. \"The winds do not harm us. We bow before them and so we do not break. You, in all your pride and strength, have so far resisted their blows. But the end is coming.\"</p><p>As the Reeds spoke a great hurricane rushed out of the north. The Oak stood proudly and fought against the storm, while the yielding Reeds bowed low. The wind redoubled in fury, and all at once the great tree fell, torn up by the roots, and lay among the pitying Reeds.</p><p>Better to yield when it is folly to resist, than to resist stubbornly and be destroyed.</p>",
    "<h1>The Crow & the Pitcher</h1><p>In a spell of dry weather, when the Birds could find very little to drink, a thirsty Crow found a pitcher with a little water in it. But the pitcher was high and had a narrow neck, and no matter how he tried, the Crow could not reach the water. The poor thing felt as if he must die of thirst.</p><p>Then an idea came to him. Picking up some small pebbles, he dropped them into the pitcher one by one. With each pebble the water rose a little higher until at last it was near enough so he could drink.</p><p>In a pinch a good use of our wits may help us out.</p>",
    "<h1>The Two Goats</h1><p>Two Goats, frisking gayly on the rocky steeps of a mountain valley, chanced to meet, one on each side of a deep chasm through which poured a mighty mountain torrent. The trunk of a fallen tree formed the only means of crossing the chasm, and on this not even two squirrels could have passed each other in safety. The narrow path would have made the bravest tremble. Not so our Goats. Their pride would not permit either to stand aside for the other.</p><p>One set her foot on the log. The other did likewise. In the middle they met horn to horn. Neither would give way, and so they both fell, to be swept away by the roaring torrent below.</p><p>It is better to yield than to come to misfortune through stubbornness.</p>",
    "<h1>The Wild Boar & the Fox</h1><p>A Wild Boar was sharpening his tusks busily against the stump of a tree, when a Fox happened by. Now the Fox was always looking for a chance to make fun of his neighbors. So he made a great show of looking anxiously about, as if in fear of some hidden enemy. But the Boar kept right on with his work.</p><p>\"Why are you doing that?\" asked the Fox at last with a grin. \"There isn't any danger that I can see.\"</p><p>\"True enough,\" replied the Boar, \"but when danger does come there will not be time for such work as this. My weapons will have to be ready for use then, or I shall suffer for it.\"</p><p>Preparedness for war is the best guarantee of peace.</p>",
    "<h1>The Heron</h1><p>A Heron was walking sedately along the bank of a stream, his eyes on the clear water, and his long neck and pointed bill ready to snap up a likely morsel for his breakfast. The clear water swarmed with fish, but Master Heron was hard to please that morning.</p><p>\"No small fry for me,\" he said. \"Such scanty fare is not fit for a Heron.\"</p><p>Now a fine young Perch swam near.</p><p>\"No indeed,\" said the Heron. \"I wouldn't even trouble to open my beak for anything like that!\"</p><p>As the sun rose, the fish left the shallow water near the shore and swam below into the cool depths toward the middle. The Heron saw no more fish, and very glad was he at last to breakfast on a tiny Snail.</p><p>Do not be too hard to suit or you may have to be content with the worst or with nothing at all.</p>",
    "<h1>The Stag & His Reflection</h1><p>A Stag, drinking from a crystal spring, saw himself mirrored in the clear water. He greatly admired the graceful arch of his antlers, but he was very much ashamed of his spindling legs.</p><p>\"How can it be,\" he sighed, \"that I should be cursed with such legs when I have so magnificent a crown.\"</p><p>At that moment he scented a panther and in an instant was bounding away through the forest. But as he ran his wide-spreading antlers caught in the branches of the trees, and soon the Panther overtook him. Then the Stag perceived that the legs of which he was so ashamed would have saved him had it not been for the useless ornaments on his head.</p><p>We often make much of the ornamental and despise the useful.</p>",
    "<h1>The Fox & the Goat</h1><p>A Fox fell into a well, and though it was not very deep, he found that he could not get out again. After he had been in the well a long time, a thirsty Goat came by. The Goat thought the Fox had gone down to drink, and so he asked if the water was good.</p><p>\"The finest in the whole country,\" said the crafty Fox, \"jump in and try it. There is more than enough for both of us.\"</p><p>The thirsty Goat immediately jumped in and began to drink. The Fox just as quickly jumped on the Goat's back and leaped from the tip of the Goat's horns out of the well</p><p>The foolish Goat now saw what a plight he had got into, and begged the Fox to help him out. But the Fox was already on his way to the woods</p><p>\"If you had as much sense as you have beard, old fellow,\" he said as he ran, \"you would have been more cautious about finding a way to get out again before you jumped in.\"</p><p>Look before you leap.</p>",
    "<h1>The Fox & the Leopard</h1><p>A Fox and a Leopard, resting lazily after a generous dinner, amused themselves by disputing about their good looks. The Leopard was very proud of his glossy, spotted coat and made disdainful remarks about the Fox, whose appearance he declared was quite ordinary.</p><p>The Fox prided himself on his fine bushy tail with its tip of white, but he was wise enough to see that he could not rival the Leopard in looks. Still he kept up a flow of sarcastic talk, just to exercise his wits and to have the fun of disputing. The Leopard was about to lose his temper when the Fox got up, yawning lazily.</p><p>\"You may have a very smart coat,\" he said, \"but you would be a great deal better off if you had a little more smartness inside your head and less on your ribs, the way I am. That's what I call real beauty.\"</p><p>A fine coat is not always an indication of an attractive mind.</p>",
    "<h1>The Wolf in Sheep\'s Clothing</h1><p>A certain Wolf could not get enough to eat because of the watchfulness of the Shepherds. But one night he found a sheep skin that had been cast aside and forgotten. The next day, dressed in the skin, the Wolf strolled into the pasture with the Sheep. Soon a little Lamb was following him about and was quickly led away to slaughter.</p><p>That evening the Wolf entered the fold with the flock. But it happened that the Shepherd took a fancy for mutton broth that very evening, and, picking up a knife, went to the fold. There the first he laid hands on and killed was the Wolf.</p><p>The evil doer often comes to harm through his own deceit.</p>",
    "<h1>The Eagle & the Beetle</h1><p>A Beetle once begged the Eagle to spare a Hare which had run to her for protection. But the Eagle pounced upon her prey, the sweep of her great wings tumbling the Beetle a dozen feet away. Furious at the disrespect shown her, the Beetle flew to the Eagle's nest and rolled out the eggs. Not one did she spare. The Eagle's grief and anger knew no bounds, but who had done the cruel deed she did not know.</p><p>Next year the Eagle built her nest far up on a mountain crag; but the Beetle found it and again destroyed the eggs. In despair the Eagle now implored great Jupiter to let her place her eggs in his lap. There none would dare harm them. But the Beetle buzzed about Jupiter\'s head, and made him rise to drive her away; and the eggs rolled from his lap.</p><p>Now the Beetle told the reason for her action, and Jupiter had to acknowledge the justice of her cause. And they say that ever after, while the Eagle\'s eggs lie in the nest in spring, the Beetle still sleeps in the ground. For so Jupiter commanded.</p><p>Even the weakest may find means to avenge a wrong.</p>",
    "<h1>The Dog & His Reflection</h1><p>A Dog, to whom the butcher had thrown a bone, was hurrying home with his prize as fast as he could go. As he crossed a narrow footbridge, he happened to look down and saw himself reflected in the quiet water as if in a mirror. But the greedy Dog thought he saw a real Dog carrying a bone much bigger than his own.</p><p>If he had stopped to think he would have known better. But instead of thinking, he dropped his bone and sprang at the Dog in the river, only to find himself swimming for dear life to reach the shore. At last he managed to scramble out, and as he stood sadly thinking about the good bone he had lost, he realized what a stupid Dog he had been.</p><p>It is very foolish to be greedy.</p>"
  ]

  function newStory(){
    var randomFable = Math.floor(Math.random()*fables.length);
    while (randomFable == currFable){ //make sure we don't pick the same fable twice in a row
      randomFable = Math.floor(Math.random()*fables.length);
    }
    currFable = randomFable;
    content.innerHTML = fables[randomFable];
  }

  button.onclick = function() { 
    newStory();
  }

  newStory();
};

